### ISSUE TITLE
Writing a large data buffer results in exception on close

### ISSUE THREAD

**Issue by HaraldVanWoerkom** [kaaveland/pyarrowfs-adlgen2#13]
When using write with a large buffer (e.g. 400MB) on an output stream, if you then close the stream, an error occurs:
(InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.

This error is caused by the flush command flushing an empty buffer (since large buffer writes automatically flush). In pyarrowfs_adlgen2.core.py, line 193 the buffer is appended. If the buffer is already empty, a 0-byte buffer is appended, which causes the error.
It seems that the data lake does not appreciate 0-length commands, so a check on the length (just ignore the call) if the length is 0 seems to be in order (probably in append_data, line 126).

Reproducing code:

```python
with open(<large file>, 'rb') as f:
    data = f.read()
cred = azure.identity.OnBehalfOfCredential(<proper ID>)
handler = pyarrowfs_adlgen2.AccountHandler.from_account_name(<account>, credential=cred)
filesystem = pyarrow.fs.PyFileSystem(handler)
o = filesystem.open_output_stream(<output file>)
o.write(data)
#The close statement causes the error. To prevent it, you can write some more bytes.
#A work-around seems to be:
#o.write(data[:-2]) 
#o.write(data[-2:-1]) 
o.close()
```

**Comment by kaaveland** [comment]
Nice job debugging this, this seems mostly solved already, thanks!

I'll try to get a new release out the door some time later today.

**Comment by kaaveland** [comment]
@HaraldVanWoerkom Would you be OK with pasting the relevant pieces of the traceback here too, in case somebody googles parts of it? I would also like to know if the stacktrace is coming from [this line](https://github.com/kaaveland/pyarrowfs-adlgen2/blob/master/pyarrowfs_adlgen2/core.py#L194) or [this line](https://github.com/kaaveland/pyarrowfs-adlgen2/blob/master/pyarrowfs_adlgen2/core.py#L196).

**Comment by HaraldVanWoerkom** [comment]
@kaaveland: Thanks for the quick response. It is line 193 (194 in my version, I'm using 0.2.0 currently, but that should not affect the bug, it is still the same code). This is the full trace:

```python
Traceback (most recent call last):
  File "C:\PythonEnv\lib\site-packages\azure\storage\filedatalake\_data_lake_file_client.py", line 461, in append_data
    return self._client.path.append_data(**options)
  File "C:\PythonEnv\lib\site-packages\azure\storage\filedatalake\_generated\operations\_path_operations.py", line 1618, in append_data
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.
RequestId:<id>
Time:2021-12-21T09:10:43.6045022Z
Code: InvalidHeaderValue
Message: The value for one of the HTTP headers is not in the correct format.
RequestId:<id>
Time:2021-12-21T09:10:43.6045022Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/dev/Local/test_writemat/test_write.py", line 26, in <module>
    o.close()
  File "pyarrow\io.pxi", line 132, in pyarrow.lib.NativeFile.close
  File "C:\PythonEnv\lib\site-packages\pyarrowfs_adlgen2\core.py", line 193, in flush
    self.append_data(self.buffer.getvalue(), self.offset, self.buffer.tell())
  File "C:\PythonEnv\lib\site-packages\pyarrowfs_adlgen2\core.py", line 127, in append_data
    data, offset, length, timeout=self.timeouts.file_client_timeout
  File "C:\PythonEnv\lib\site-packages\azure\storage\filedatalake\_data_lake_file_client.py", line 463, in append_data
    process_storage_error(error)
  File "C:\PythonEnv\lib\site-packages\azure\storage\filedatalake\_deserialize.py", line 180, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.
RequestId:<id>
Time:2021-12-21T09:10:43.6045022Z
Code: InvalidHeaderValue
Message: The value for one of the HTTP headers is not in the correct format.
RequestId:<id>
Time:2021-12-21T09:10:43.6045022Z
```

**Comment by kaaveland** [comment]
I'm not sure where to fix this. It's the least intrusive to do this in the close/flush path of the code -- which will still leave this error propagating whenever somebody writes "empty". I could've also fixed this in the append_data path, which is called by the flush/close path, which but that feels a lot like swallowing/hiding error conditions. So I think we're going to do it in the flush/close path for now.

**Comment by HaraldVanWoerkom** [comment]
I'm fine with the solution you propose.

If I look at the code I can see that a write of a 0-length object is handled properly, so the PyFileSystem interface is observed. 

The Azure interface is not very clear on 0-length buffers, but given that the return value of append_data is the response header, it is reasonable that the interface should observe the same rules as the storage service itself and that is not to allow 0-length buffers.

**Comment by kaaveland** [comment]
Should be fixed now: https://pypi.org/project/pyarrowfs-adlgen2/0.2.3/
