### ISSUE TITLE
DatalakeGen2File read() should increment self.loc

### ISSUE THREAD

**Issue by rafalwijata** [kaaveland/pyarrowfs-adlgen2#25]

**Comment by kaaveland** [comment]
```
    def read(self, length=-1):
        if self.mode != 'rb':
            raise ValueError("File not in read mode")
        if self.closed:
            raise ValueError('I/O on closed file')
        if length < 0:
            length = self.get_file_properties().size - self.loc
        if length == 0:
            return b''

        return self.download_file(self.loc, length).readall()
```

Don't know how I missed that, should be a simple fix. I'll try to get this released later today.

**Comment by rafalwijata** [comment]
Additionally, after fix read fails when reading from EOF or beyond

**Comment by rafalwijata** [comment]
And not a bug but huge performance hit: seek() always calls self.get_file_properties().size could do it only in case of whence == 2
In my sources I just created cached _getSize() method (usefull in seek/flush/read)

**Comment by kaaveland** [comment]
Should be fixed in https://pypi.org/project/pyarrowfs-adlgen2/0.2.5/

**Comment by rafalwijata** [comment]
introduced self._eof should be set not only in read() but in seek() as well. basically caching file size seems good idea.
