### ISSUE TITLE
azure.core.exceptions.ServiceRequestError need to increase Timeout

### ISSUE THREAD

**Issue by sisaberi** [kaaveland/pyarrowfs-adlgen2#6]
First of all great effort I've tried out this package and it makes my life a lot easier.

We're experiencing lots of azure.core.exceptions.ServiceRequestError due to timeouts we we're able to trace back the problem to `get_paths(path, recursive=False)` in core.py get_file_info_selector() here we should be able to pass a higher timeout. For that to work we would need a param that would be passed on to that function call.

**Comment by kaaveland** [comment]
Will need to pass the timeout to constructors, since the pyarrow interfaces do not have it as far as I know. I'll take a stab at this some time this week, it doesn't look too hard, but I want to think about how to best do this since practically everything can time out. 

Would also like having an "escape hatch" to pass arbitrary extra params to the sdk without too much fuss

**Comment by kaaveland** [comment]
Here's an attempt: https://github.com/kaaveland/pyarrowfs-adlgen2/pull/7

This:
- Passed the tests
- Enables overriding all interactions with the SDK calls (by subclassing or monkeypatching)
- Sets timeouts per-sdk class
- Provide a different `Timeouts` class to use a different scheme for timeouts (eg. default global timeout or whatever)

What's not so nice is that it's verbose (each SDK method name is written like 3 places) so it's error prone to call new methods, but we should be mostly stable on that anyway.

**Comment by sisaberi** [comment]
Thanks I had not expected a solution so fast. 
Went over it and it LGTM.
When will you create a new release?

**Comment by kaaveland** [comment]
I've released 0.2.0 now.

You can try constructing with 'timeouts=pyarrowfs_adlgen2.Timeouts(file_system_timeout=60)` and see if that works for you (the `get_paths` call belongs to `azure.storage.filedatalake.FileSystemClient`).

Closing for now, get in touch again if this doesn't fix the problem!
