### ISSUE TITLE
write schema and write metadata question

### ISSUE THREAD

**Issue by mzhukovs** [kaaveland/pyarrowfs-adlgen2#8]
Hi, is there anyway to read and write JUST the schema or metadata from the parquet file in ADLS gen 2? This would be super useful but as of now can't seem to find a way and thought your library may help - please let me know your thoughts.

https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_schema.html?highlight=read_schema 
https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_metadata.html

The where parameter seems to require a local uri or NativeFile so not sure if it's possible to write:
https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_metadata.html?highlight=write_meta

**Comment by mzhukovs** [comment]
Update: looked more closely at the docs for dataset and it seems reading these things is indeed easily achievable as the dataset does not read in the actual file until you call to_table(), so to READ the schema via ds.schema and ds.schema.metadata is no issue, but to WRITE it it seems one must call to_table() - are you aware of a way to update column names, metadata, etc. without reading the data contents?

**Comment by kaaveland** [comment]
Yeah, you can read `ds.schema` for your original question.

The `write_metadata` you're linking to, will forward any kwargs it doesn't know to https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetWriter.html#pyarrow.parquet.ParquetWriter which accepts a filesystem argument -- but I don't know if that class works with third-party file systems.

I don't know of any way to write only the metadata/schema using the new dataset API. Closest thing I can find is https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Dataset.html#pyarrow.dataset.Dataset.replace_schema -- but this won't update anything on the file system.

Maybe you should ask over at user@arrow.apache.org (see https://arrow.apache.org/community/) ?

**Comment by kaaveland** [comment]
Closed this, because this is more general than pyarrowfs-adlgen2, this is more about APIs in arrow that accept `filesystem=`.

**Comment by mzhukovs** [comment]
Thanks @kaaveland
